Working routing covers all states
sashkivna/MyToDoAppWithRouting pull request #4
Opened 2018-10-16 13:15 UTC by sashkivna

version with deleted comments and +- beautified code

2018-10-16 13:24 UTC, r0ss0neri requested changes

2018-10-16 13:24 UTC, r0ss0neri commented on app/components/todo/todo.directive.js
> +                        console.log($scope.tasks);
remove `console.log` statements if they are not needed

2018-10-16 13:24 UTC, r0ss0neri commented on app/components/todo/todo.directive.js
> +            controller: function () {
remove controller

2018-10-16 13:24 UTC, r0ss0neri commented on app/components/todo/todo.directive.js
> +                        $scope.tasks.push({task: $scope.title, cteated: datetime, done: false});
format 
    
    $scope.tasks.push({
        task: $scope.title, 
        created: datetime, 
        done: false
    });

2018-10-16 13:24 UTC, r0ss0neri commented on app/components/todo/todo.service.js
> +            cauurentUser = userService.getCurrentUser();
blank line after

2018-10-16 13:24 UTC, r0ss0neri commented on app/components/todo/todo.service.js
> +            }
blank line after

2018-10-16 13:24 UTC, r0ss0neri commented on app/components/todo/todo.service.js
> +            users: users,
`users ` -> `getAllUserDescriptors`

2018-10-16 13:24 UTC, r0ss0neri commented on app/login/register-controller.js
> +    .controller('loginController', function ($scope, userService, $state) {
don't forget to sort injectors alphabetically 

- angular services
- then third party libraries 
- app dependencies

2018-10-16 13:24 UTC, r0ss0neri commented on app/main/main.controller.js
> +        $scope.tasks = JSON.parse(localStorage.getItem('tasks')) || [];
can we use todoService to get tasks instead of localStorage?

2018-10-16 13:24 UTC, r0ss0neri commented on app/users-todo/users-todo.controller.js
> +            debugger;
remove debugger

2018-10-16 13:58 UTC, sashkivna commented on app/components/todo/todo.directive.js
> +                        console.log($scope.tasks);
done

2018-10-16 13:59 UTC, sashkivna commented on app/components/todo/todo.directive.js
> +            controller: function () {
done

2018-10-16 14:00 UTC, sashkivna commented on app/components/todo/todo.directive.js
> +                        $scope.tasks.push({task: $scope.title, cteated: datetime, done: false});
done

2018-10-16 14:00 UTC, sashkivna commented on app/components/todo/todo.service.js
> +            cauurentUser = userService.getCurrentUser();
done

2018-10-16 14:01 UTC, sashkivna commented on app/login/register-controller.js
> +    .controller('loginController', function ($scope, userService, $state) {
changed

2018-10-16 14:03 UTC, sashkivna commented on app/users-todo/users-todo.controller.js
> +            debugger;
deleted

2018-10-16 14:05 UTC, sashkivna commented on app/main/main.controller.js
> +        $scope.tasks = JSON.parse(localStorage.getItem('tasks')) || [];
changed

2018-10-17 08:38 UTC, r0ss0neri requested changes

2018-10-17 08:38 UTC, r0ss0neri commented on app/users-todo/users-todo.controller.js
> +        $scope.users = JSON.parse(localStorage.getItem('users')) || [];
use `userService` to get all users

2018-10-17 08:44 UTC, sashkivna commented on app/users-todo/users-todo.controller.js
> +        $scope.users = JSON.parse(localStorage.getItem('users')) || [];
done

2018-10-17 08:55 UTC, merged